#########################################################
# <COPYRIGHT_TAG>
#########################################################
unexport LDFLAGS
all:
	 bash -c "cmake -H. -B./build && make -C ./build"
clean:
	 rm -rf ./build
